micronaut:
  application:
    name: nossaCasaDoCodigo

datasources:
  default:
    url: ${DB_URL:`jdbc:postgresql://localhost:5432/cdc`}
    driverClassName: org.postgresql.Driver
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}

jpa:
  default:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
  format_sql: true
  show_sql: true
jpa.default.properties.hibernate.hbm2ddl.auto: update
